var lapenshard = [
	shards = [
		{
			"title": "",
		},{
			"title": "Pride Bolt Red Lapenshard",
			"color": "red",
			"requirement": "Requires Level 60</span></p><p><span class='info_gray'>Exceptional Red lapenshard",
			"skillinfo": "Fire <span class='info_blue'></span> electric bolt <span class='info_blue'></span> m in front of you. Targets take <span class='info_blue'></span> damage and are stunned for <span class='info_blue'></span> sec taking an additional <span class='info_blue'></span> damage per second.",
			"skilltext": [
				"1,9,158%,20,158%",
				"1,9,171%,20,171%",
				"1,9,184%,20,184%",
				"1,9,191%,20,191%",
				"1,9,204%,20,204%",
				"1,9,224%,20,224%",
				"1,9,244%,20,244%",
				"1,9,268%,20,268%",
				"1,9,301%,20,301%",
				"1,9,335%,20,335%",
			]
		},{
			"title": "Lumarigon's Pride Red Lapenshard",
			"color": "red",
			"requirement": "Requires Level 60</span></p><p><span class='info_gray'>Exceptional Red lapenshard",
			"skillinfo": "Increases physical and magic attack by <span class='info_blue'></span> and decreases defense by <span class='info_blue'></span> for <span class='info_blue'></span> sec.",
			"skilltext": [
				"36,50%,10",
				"42,50%,10",
				"54,50%,10",
				"66,50%,10",
				"78,50%,10",
				"96,50%,10",
				"120,50%,10",
				"144,50%,10",
				"174,50%,10",
				"216,50%,10",
			]
		},{
			"title": "Sword of Time Red Lapenshard",
			"color": "red",
			"requirement": "Requires Level 60</span></p><p><span class='info_gray'>Exceptional Red lapenshard",
			"textbasic": "Basic Attributes<br> • Sword of Time",
			"skillinfo": "Launch a sword at <span class='info_blue'></span> enemy within <span class='info_blue'></span> m and increase attack speed and movement speed by <span class='info_blue'></span> for <span class='info_blue'></span> sec. The sword attacks <span class='info_blue'></span> times dealing <span class='info_blue'></span>. <span class='info_blue'></span> and <span class='info_blue'></span> damage to enemies within <span class='info_blue'></span> m. When skill break is <span class='info_blue'></span> in Emerald Prison damage is doubled. Sword of Time has <span class='info_blue'></span> uses. Regain <span class='info_blue'></span> use after every cooldown.",
			"skilltext": [
				"1,9,2%,3,3,162%,243%,408%,1.5,12000,20,1",
				"1,9,2%,3,3,168%,252%,420%,1.5,14400,20,1",
				"1,9,2%,3,3,174%,261%,432%,1.5,16800,20,1",
				"1,9,2%,3,3,180%,270%,450%,1.5,19200,20,1",
				"1,9,2%,3,3,186%,282%,468%,1.5,21600,20,1",
				"1,9,2%,3,3,195%,294%,489%,1.5,24000,20,1",
				"1,9,2%,3,3,204%,306%,510%,1.5,26400,20,1",
				"1,9,2%,3,3,210%,318%,531%,1.5,28800,20,1",
				"1,9,2%,3,3,225%,339%,567%,1.5,31200,20,1",
				"1,9,2%,3,3,243%,366%,612%,1.5,36000,20,1",
			]
		},{
			"title": "Moonlight Slash Red Lapenshard",
			"color": "red",
			"requirement": "Requires Level 70</span></p><p><span class='info_gray'>Exceptional Red lapenshard",
			"skillinfo": "Veliche appears and attacks enemies in front of you dealing <span class='info_blue'></span> and causing them to bleed for <span class='info_blue'></span> sec. Bleeding enemies periodically take <span class='info_blue'></span> damage.",
			"skilltext": [
				"457%,10,69%",
				"548%,10,82%",
				"685%,10,103%",
				"822%,10,123%",
				"1005%,10,151%",
				"1233%,10,185%",
				"1507%,10,226%",
				"1827%,10,274%",
				"2238%,10,336%",
				"2741%,10,411%",
			]
		},{
			"title": "Gigantica Beam Red Lapenshard",
			"color": "red",
			"requirement": "Requires Level 70</span></p><p><span class='info_gray'>Exceptional Red lapenshard",
			"skillinfo": "Gigantica fires a powerful laser at enemies in front of you dealing <span class='info_blue'></span> damage and electrifying them for <span class='info_blue'></span> sec. Electrified targets have a chance to take an additional <span class='info_blue'></span> damage when hit.",
			"skilltext": [
				"1027%,10,154%",
				"1233%,10,185%",
				"1541%,10,231%",
				"1850%,10,277%",
				"2261%,10,339%",
				"2775%,10,416%",
				"3391%,10,508%",
				"4111%,10,616%",
				"5036%,10,755%",
				"6166%,10,925%",
			]
		},{
			"title": "Erda's Chill Blue Lapenshard",
			"color": "blue",
			"requirement": "Requires Level 60</span></p><p><span class='info_gray'>Exceptional Blue lapenshard",
			"jobskills": [
				"KNIGHT | Conviction Strike",
				"BERSERKER | Aerial Smash",
				"WIZARD | Ice Cream Time",
				"PRIEST | Light Spear",
				"ARCHER | Flame Arrow",
				"HEAVY GUNNER | Fire Bomber",
				"THIEF | Savage Strikes",
				"ASSASSIN | All-in-One",
				"RUNEBLADE | Blade Whip",
				"SOUL BINDER | Spirit Crush",
				"STRIKER | Shockwave Punch",
			],
			"skillinfo": "has a chance to deal an additional <span class='info_blue'></span> damage to the enemy.",
			"skilltext": [
				"169%",
				"202%",
				"253%",
				"303%",
				"371%",
				"455%",
				"556%",
				"674%",
				"826%",
				"1012%",
			]
		},{
			"title": "Master's Malice Blue Lapenshard",
			"color": "blue",
			"requirement": "Requires Level 60</span></p><p><span class='info_gray'>Exceptional Blue lapenshard",
			"jobskills": [
				"KNIGHT | Light Bringer",
				"BERSERKER | Parry the Moon",
				"WIZARD | Perfect Storm",
				"PRIEST | Heaven's Wrath",
				"ARCHER | Multi-Drive Shot",
				"HEAVY GUNNER | Demolition Cannon",
				"THIEF | Volatile Vials",
				"ASSASSIN | Binding Punishment",
				"RUNEBLADE | Phantasm Slash",
				"SOUL BINDER | Spirit Bound",
				"STRIKER | Double-Fist Smash",
			],
			"skillinfo": "has a chance to deal an additional <span class='info_blue'></span> damage and to decrease phyiscal and magic attack by <span class='info_blue'></span> for <span class='info_blue'></span> sec.",
			"skilltext": [
				"843%,2%,8",
				"1012%,2%,8",
				"1265%,2%,8",
				"1517%,2%,8",
				"1855%,2%,8",
				"2276%,2%,8",
				"2782%,2%,8",
				"3372%,2%,8",
				"4131%,2%,8",
				"5058%,2%,8",
			]
		},{
			"title": "Bjorn's Artistry Blue Lapenshard",
			"color": "blue",
			"requirement": "Requires Level 60</span></p><p><span class='info_gray'>Exceptional Blue lapenshard",
			"jobskills": [
				"KNIGHT | Heaven's Judgment",
				"BERSERKER | Blood Slash",
				"WIZARD | Little Meteor",
				"PRIEST | Divine Wave",
				"ARCHER | Spiral Arrow",
				"HEAVY GUNNER | Hyper Giga Cannon",
				"THIEF | Deadly Strikes",
				"ASSASSIN | Assassin's Circle",
				"RUNEBLADE | Rune Ignition",
				"SOUL BINDER | Soul Harmony",
				"STRIKER | Spin Kick",
			],
			"skillinfo": "has a chance to increase attack speed by <span class='info_blue'></span> for <span class='info_blue'></span> sec.",
			"skilltext": [
				"3%,20",
				"4%,20",
				"5%,20",
				"6%,20",
				"7%,20",
				"8%,20",
				"10%,20",
				"12%,20",
				"15%,20",
				"18%,20",
			]
		},{
			"title": "Pink Bean's Prank Blue Lapenshard",
			"color": "blue",
			"requirement": "Requires Level 60</span></p><p><span class='info_gray'>Exceptional Blue lapenshard",
			"jobskills": [
				"KNIGHT | Cyclone Shield",
				"BERSERKER | Squall",
				"WIZARD | Barbecue Party",
				"PRIEST | Purifying Light",
				"ARCHER | Piercing Arrow",
				"HEAVY GUNNER | Sky Hunter",
				"THIEF | Shadow Step",
				"ASSASSIN | Dark Mire",
				"RUNEBLADE | Dimension Blade",
				"SOUL BINDER | Soul Flock",
				"STRIKER | Setup Kick",
			],
			"skillinfo": "has a chance to increase physical and magic attack by <span class='info_blue'></span> and increase body size by <span class='info_blue'></span> for <span class='info_blue'></span> sec.",
			"skilltext": [
				"5%,30%,8",
				"7%,30%,8",
				"8%,30%,8",
				"10%,30%,8",
				"12%,30%,8",
				"15%,30%,8",
				"18%,30%,8",
				"22%,30%,8",
				"27%,30%,8",
				"33%,30%,8",
			]
		},{
			"title": "Space Rift Blue Lapenshard",
			"color": "blue",
			"requirement": "Requires Level 60</span></p><p><span class='info_gray'>Exceptional Blue lapenshard",
			"jobskills": [
				"KNIGHT | Divine Retribution and Guardian's Wings",
				"BERSERKER | Skull Splitter and Raging Soul",
				"WIZARD | Dual Cast and Ember",
				"PRIEST | Scathing Light and Vitality",
				"ARCHER | Ranger's Focus and Greater Sharp Eyes",
				"HEAVY GUNNER | Focused Fire and Plasma Chain",
				"THIEF | Battle Plan and Critical Slice",
				"ASSASSIN | Redoubled Pain and Shadow Stance",
				"RUNEBLADE | Quintuple Cut and Rune Trigger",
				"SOUL BINDER | Vision Torrent and Triune Link",
				"STRIKER | Meridian Flow and Spiral Cannon",
			],
			"textbasic": "Basic Attributes<br> • Space Rift",
			"skillinfo": "have a chance to deal <span class='info_blue'></span> damage. Inflicts <span class='info_blue'></span> skill break (subject to cooldown) and double damage in Terminus of Time.",
			"skilltext": [
				"281%,5133",
				"337%,6160",
				"422%,7187",
				"506%,8213",
				"618%,9240",
				"759%,10267",
				"927%,11293",
				"1124%,12320",
				"1377%,13347",
				"1686%,15400",
			]
		},{
			"title": "",
			"color": "blue",
			"requirement": "Requires Level 70</span></p><p><span class='info_gray'>Exceptional Blue lapenshard",
			"texts": [
				"",
			]
		},{
			"title": "",
			"color": "blue",
			"requirement": "Requires Level 70</span></p><p><span class='info_gray'>Exceptional Blue lapenshard",
			"texts": [
				"",
			]
		},{
			"title": "",
			"color": "blue",
			"requirement": "Requires Level 70</span></p><p><span class='info_gray'>Exceptional Blue lapenshard",
			"texts": [
				"",
			]
		},{
			"title": "",
			"color": "blue",
			"requirement": "Requires Level 70</span></p><p><span class='info_gray'>Exceptional Blue lapenshard",
			"texts": [
				"",
			]
		},{
			"title": "",
			"color": "green",
			"requirement": "Requires Level 60</span></p><p><span class='info_gray'>Exceptional Green lapenshard",
			"texts": [
				"",
			]
		},{
			"title": "Guardian's Rage Green Lapenshard",
			"color": "green",
			"requirement": "Requires Level 60</span></p><p><span class='info_gray'>Exceptional Green lapenshard",
			"skillinfo": "Increases physical/magic damage by <span class='info_blue'></span> and decreases defense by <span class='info_blue'></span>.",
			"skilltext": [
				"1%,1%",
				"1.2%,1.2%",
				"1.5%,1.5%",
				"1.8%,1.8%",
				"2.2%,2.2%",
				"2.7%,2.7%",
				"3.3%,3.3%",
				"4%,4%",
				"4.9%,4.9%",
				"6%,6%",
			]
		},{
			"title": "Madrakan Trooper Green Lapenshard",
			"color": "green",
			"requirement": "Requires Level 60</span></p><p><span class='info_gray'>Exceptional Green lapenshard",
			"skillinfo": "Increases health by <span class='info_blue'></span> and movement speed by <span class='info_blue'></span>.",
			"skilltext": [
				"275,1%",
				"330,1%",
				"416,1%",
				"500,1%",
				"610,2%",
				"750,2%",
				"915,2%",
				"1112,2%",
				"1360,3%",
				"1665,3%",
			]
		},{
			"title": "Eupheria's Protection Green Lapenshard",
			"color": "green",
			"requirement": "Requires Level 60</span></p><p><span class='info_gray'>Exceptional Green lapenshard",
			"textbasic": "Basic Attributes<br> • Eupheria's Protection",
			"skillinfo": "Eupheria watches over you increasing all damage by <span class='info_blue'></span> and health by <span class='info_blue'></span>. If health drops below <span class='info_blue'></span> your carelessness incurs Eupheria's wrath and take <span class='info_blue'></span> damage per second for <span class='info_blue'></span> sec. Effects are doubled in Azur Grave and each hit inflicts <span class='info_blue'></span> skill break at regular intervals.",
			"skilltext": [
				"1%,220,20%,1.5%,20,5133",
				"1.2%,264,20%,1.5%,20,6160",
				"1.5%,333,20%,1.5%,20,7187",
				"1.8%,400,20%,1.5%,20,8213",
				"2.2%,488,20%,1.5%,20,9240",
				"2.7%,600,20%,1.5%,20,10267",
				"3.3%,732,20%,1.5%,20,11293",
				"4%,890,20%,1.5%,20,12320",
				"4.9%,1088,20%,1.5%,20,13347",
				"6%,1332,20%,1.5%,20,15400",
			]
		},{
			"title": "Nairin's Air Support Green Lapenshard",
			"color": "green",
			"requirement": "Requires Level 70</span></p><p><span class='info_gray'>Exceptional Green lapenshard",
			"skillinfo": "Attacks have a chance to summon a supply drop. Nairin's rations restore <span class='info_blue'></span> health and increase physical and magic damage by <span class='info_blue'></span> for <span class='info_blue'></span> min.",
			"skilltext": [
				"1650,1.3%,3",
				"1980,1.6%,3",
				"2475,2.0%,3",
				"2970,2.4%,3",
				"3630,2.9%,3",
				"4455,3.6%,3",
				"5445,4.4%,3",
				"6600,5.3%,3",
				"8085,6.5%,3",
				"9900,8.0%,3",
			]
		},{
			"title": "Wandering Blade Green Lapenshard",
			"color": "green",
			"requirement": "Requires Level 70</span></p><p><span class='info_gray'>Exceptional Green lapenshard",
			"skillinfo": "Paika's power fills this lapenshard increasing critical damage by <span class='info_blue'></span> and decreasng accuracy by <span class='info_blue'></span>.",
			"skilltext": [
				"70,3",
				"84,3",
				"105,3",
				"126,3",
				"154,3",
				"189,3",
				"231,3",
				"280,3",
				"343,3",
				"420,3",
			]
		},{
			"title": "Celine's Heart Red Lapenshard",
			"color": "red",
			"requirement": "Requires Level 60</span></p><p><span class='info_gray'>Exceptional Red lapenshard",
			"skillinfo": "Play Celine's song <span class='info_blue'></span> m in <span class='info_blue'></span> directions. Targets of the song take <span class='info_blue'></span> damage and are stunned for <span class='info_blue'></span> sec.",
			"skilltext": [
				"12,3,552%,1",
				"12,3,599%,1",
				"12,3,646%,1",
				"12,3,669%,1",
				"12,3,716%,1",
				"12,3,787%,1",
				"12,3,857%,1",
				"12,3,939%,1",
				"12,3,1057%,1",
				"12,3,1174%,1",
			]
		}
	]
];
